### ISSUE TITLE
Functions not displaying

### ISSUE THREAD

**Issue by MildredOkoye** [RFVenter/icofund#1]
Is there any reason why the two functions balanceOf and tokenPrice do not display when the contract are executed using the ethereum wallet?

**Comment by RFVenter** [comment]
Hello @MildredOkoye. Please send your Ethereum Wallet version. All the functions on 0xd49bBB00b5169e47E54D3cDCE71576D026eabCC9 works with Ethereum Wallet and Ethereum Mist. You may also check the contract at MyEthereumWallet. There has been a lot of issues with Ethereum Wallet and I don't suggest that you use that software.

**Comment by MildredOkoye** [comment]
Thanks @RFVenter  for replying. I am using version 0.8.9 of the Ethereum Wallet. When I deploy the contract with the wallet and open the contract, in the 'pick fuction' drop down menu,  balanceOf and tokenPrice are not among the list

**Comment by MildredOkoye** [comment]
Also if the creator of the contract deploys the contract, what function can user execute to send ether to the contract. Seeing that apart from the transfer function and the  'balanceOf and tokenPrice'(which are not displayed) the rest of the function can only be executed by the owner or creator.

**Comment by MildredOkoye** [comment]
Thanks @RFVenter  for your reply. I was wrong, as I wrong as I was expecting to see those function in the drop down list. It sorted out now

**Comment by RFVenter** [comment]
OK then. Remember that the contract is simple. Any Ethereum address that sends Ether to that contract will have tokens allocated to its address. The amount of tokens is calculated based on the current value of the tokens (updated by the token owner, and calculated according to its underlying assets).
